### ISSUE TITLE
Increase automatic filename detection

### ISSUE THREAD

**Issue by texdc** [randomchance/vscode-logstash-configuration-syntax#7]
Thanks for this extension.  I've just installed it, but it doesn't recognize my jinja template.

My filename is `logstash.conf.j2` and it's not recognized.  However, if I change the filename to `foo.logstash.conf.j2`, the extension provides syntax highlights as expected.

**Comment by randomchance** [comment]
ahh, I see. 

Just updating the regex would be fast but I should really put that into the configuration. 

For right now I believe you can manually select the "language" of any file with the `Change Language Mode` command.

**Comment by randomchance** [comment]
`CTRL+SHIFT+P` -> `Change Language Mode` 

I'll try and look into adding the configuration, but I'm going to be pretty busy for the next week or two :(

**Comment by randomchance** [comment]
That makes sense. I'm going to be traveling for business but I'll try to get that change pushed out.
